### ISSUE TITLE
Ouster Lidar Synchronization Bug

### ISSUE THREAD

**Issue by OAHC2022** [ut-amrl/coda-devkit#18]
I believe this is a bug https://github.com/ut-amrl/coda-devkit/blob/main/helpers/bagdecoder.py#L206. Here you are using the last timestamp of the lidar packet to construct your point cloud message, but I believe the default ouster lidar uses the first lidar packet timestamp to construct the point cloud. This could cause your pointcloud time synchronization off by 0.1 second.

**Comment by artzha** [comment]
Thanks for bringing up this issue! This bug was introduced in the code refactor for commit 39bf658. To fix it, we implement a method similar to the Ouster SDK method for obtaining the ROS timestamp: https://github.com/ouster-lidar/ouster-ros/blob/5a08f89e21dabfb78ae359f9bfc4ba869a275104/src/lidar_packet_handler.h#L151.

We take the received ROS timestamp for the latest LiDAR packet and offset it using the relative time offset between the latest and earliest lidar packets for each point cloud. This gives us the interpolated timestamp for approximately when the first LiDAR packet was received. The code changes implementing this bugfix can be found here: https://github.com/ut-amrl/coda-devkit/blob/7356fc2bb5cff5ef315606226e872c6daa4a2901/helpers/sensors.py#L107
